packages:
  # all packages in subdirs of packages/
  - 'packages/*'
  - 'platforms/*'
  - 'htmls/*'
  - 'bugs/*'
  # exclude packages that are inside test directories
  - '!**/test/**'
  - '!**/examples/**'
