(function () {
	'use strict';

	const e=new class{constructor(){this.handlers={},this.init();}init(){chrome.runtime.onMessage.addListener((async(e,a,s)=>{const{type:t,payload:n}=e,r=this.handlers[t];if(r){s({data:await r({data:n,sender:a})});}else s({data:"没找到函数"});return !0}));}sendMessage(e,a){return new Promise((s=>{chrome.runtime.sendMessage({type:e,payload:a},(e=>{s({data:e});}));}))}async sendTabMessage(e,a){const[s]=await chrome.tabs.query({active:!0,currentWindow:!0});return new Promise((t=>{chrome.tabs.sendMessage(s.id,{type:e,payload:a},(e=>{t({data:e});}));}))}onMessage(e,a){this.handlers[e]=a;}};

	class s$1{constructor({self:s,other:t}){this.handlers={},this.callbacks={},this.self="",this.other="",this.init=()=>{window.addEventListener("message",(async s=>{var t,e;const{selfKey:a,otherKey:i}=this,{from:n,eventName:r,params:l,callback:h,status:o}=s.data;if(n!==i)return;if("res"===o)return null==(e=(t=this.callbacks)[h])?void 0:e.call(t,l);if(!r.startsWith(this.self))return;const c=this.handlers[r],f=await(null==c?void 0:c(l));window.postMessage({from:a,status:"res",eventName:r,params:f,callback:h},"*");}));},this.on=async(s,t)=>{this.handlers[s]=t;},this.call=async(s,t)=>{const{callbacks:e}=this,a=`hytest_extension_${Date.now()}`;return window.postMessage({from:this.selfKey,status:"req",eventName:s,params:t,callback:a},"*"),new Promise((s=>{e[a]=function(t){delete e[a],s(t);};}))},this.self=s,this.other=t,this.init();}get selfKey(){return `${this.self}:extension`}get otherKey(){return `${this.other}:extension`}}

	const s=new s$1({self:"content",other:"page"});window.pageExtensionSDK=s$1,chrome.runtime.onMessage.addListener((async(e,t,a)=>{const{type:n,payload:r}=e;if(!n.startsWith("page:"))return;a({data:await s.call(n,r)});})),window.addEventListener("message",(async t=>{const{from:s,eventName:a,params:n,callback:r,status:o}=t.data;if("page:extension"!==s)return;if(!["server:","popup:"].find((e=>a.startsWith(e))))return;const c=await e.sendMessage(a,n);window.postMessage({from:"content:extension",status:"res",eventName:a,params:c,callback:r},"*");})),window.addEventListener("load",(function(){const e=document.body;var t=document.createElement("script");t.setAttribute("type","text/javascript"),t.setAttribute("src",chrome.runtime.getURL("sdk.js")),e.appendChild(t);})),async function(){e.onMessage("server:fetch-iframe-src",(async({data:e,sender:t})=>({src:"test.com/hello",host:"test.com"})));}();

}());
